// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDRE5i8oNKdwyWGmTfuKi-H4b82jDJNI',
    appId: '1:1069676299148:web:844f6289b91a86b0030ca9',
    messagingSenderId: '1069676299148',
    projectId: 'tomas-s-website-bcfae',
    authDomain: 'tomas-s-website-bcfae.firebaseapp.com',
    storageBucket: 'tomas-s-website-bcfae.firebasestorage.app',
    measurementId: 'G-95SZFRWTGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54eBBdjWBHJitEmHdF0YxOE0Y3g3WEsk',
    appId: '1:1069676299148:android:1a760463b8948ae5030ca9',
    messagingSenderId: '1069676299148',
    projectId: 'tomas-s-website-bcfae',
    storageBucket: 'tomas-s-website-bcfae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOI3SnFRG-friI4vXLEuPvG9vcQ8IrQsE',
    appId: '1:1069676299148:ios:8a54ec9ffbeca09b030ca9',
    messagingSenderId: '1069676299148',
    projectId: 'tomas-s-website-bcfae',
    storageBucket: 'tomas-s-website-bcfae.firebasestorage.app',
    iosBundleId: 'com.example.tomasWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOI3SnFRG-friI4vXLEuPvG9vcQ8IrQsE',
    appId: '1:1069676299148:ios:8a54ec9ffbeca09b030ca9',
    messagingSenderId: '1069676299148',
    projectId: 'tomas-s-website-bcfae',
    storageBucket: 'tomas-s-website-bcfae.firebasestorage.app',
    iosBundleId: 'com.example.tomasWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkDRE5i8oNKdwyWGmTfuKi-H4b82jDJNI',
    appId: '1:1069676299148:web:575fcd2143c9ee8b030ca9',
    messagingSenderId: '1069676299148',
    projectId: 'tomas-s-website-bcfae',
    authDomain: 'tomas-s-website-bcfae.firebaseapp.com',
    storageBucket: 'tomas-s-website-bcfae.firebasestorage.app',
    measurementId: 'G-Y5VRK6LTWQ',
  );
}
